---
  - name: create build param template temporarily
    template:
      src: ./templates/build.param.j2
      dest: './templates/build.param'
    vars:
      GIT_REF: 'pull/{{ PR }}/head'

  - name: create build in tools namespace using head/pulls/{{ PR }} as ref 
    shell: >
      oc process -n "{{ tools_namespace }}" -f "../templates/react-frontend/bc.yaml" --param-file="./templates/build.param" | 
      oc apply -n "{{ tools_namespace }}" -f -

  - name: start build
    shell: oc -n "{{ tools_namespace }}" start-build {{ react_infra_name }}-{{ version }}

  - name: cleanup run (delete temp files)
    file:
      path: ./templates/build.param
      state: absent