---
  - name: check pr exists in tools
    shell: oc -n {{ tools_namespace }} get imagestreamtag/{{ react_infra_name }}:{{ version }}
    register: ist
    ignore_errors: yes

  - debug: 
      msg: 
        - Image Tag {{ version }} does not exist in {{ tools_namespace }}. 
        - This is because either you have not run ansible-playbook build-react.yaml -e PR={{ PR }}
        - Or the buildconfig has been run but isn't complete
        - OR the build failed
    when: "'No resources found' in ist.stderr"
