---
  - name: check pr exists in tools
    shell: oc -n {{ tools_namespace }} get imagestreamtag/{{ dev_imagestream }}:{{ version }}
    register: ist
    ignore_errors: yes

  - debug: 
      msg: 
        - Image Tag {{ version }} does not exist in {{ tools_namespace }}. 
        - This is because either you have not run ansible-playbook build-react.yaml -e PR={{ PR }}
        - Or the buildconfig has been run but isn't complete
        - OR the build failed
    when: "'No resources found' in ist.stderr"
  
  - name: create deploy param template temporarily
    template:
      src: ./templates/deploy.param.j2
      dest: './templates/deploy.param'
    vars:
      IMAGE_TAG: '{{ version }}'
  - name: deploy a dev instance of {{ PR }} in {{ dev_namespace }} namespace
    shell: >
      oc process -f "../templates/react-frontend/dc.yaml" --param-file="./templates/deploy.param" | 
      oc apply -n "{{ dev_namespace }}" -f -
  - name: cleanup run (delete temp files)
    file:
      path: ./templates/deploy.param
      state: absent