---

- name: Wait for "{{ kind }}" object {{ name }} pods to get into ready state in {{ namespace }} 
  k8s_info:
    api_version: v1
    kind: "{{ kind }}"
    name: "{{ name }}"
    namespace: "{{ namespace }}"
  register: result
  until: (result.resources[0].status.readyReplicas is defined) and (result.resources[0].status.readyReplicas == result.resources[0].spec.replicas)
  delay: 15
  retries: 20
  ignore_errors: True
- name: Decide on rolling back
  set_fact:
    object_ready: "{{ (result.resources[0].status.readyReplicas is defined) and (result.resources[0].status.readyReplicas == ready_status) }}"
    is_dc: "{{ kind == 'dc' }}"

- debug: 
    msg:
      - "--------- Failed deployment of {{ kind }}/{{ name }}  ---------"
      - "result.resources[0].status.readyReplicas ready replicas"
      - "result.resources[0].spec.replicas configured replicas"
  when: not object_ready
