---
tools_namespace: c0cce6-tools
dev_namespace: c0cce6-dev
test_namespace: c0cce6-test
prod_namespace: c0cce6-prod
github_repo: digital.gov.bc.ca
github_owner: bcgov
react_infra_name: digital-gov-frontend
strapi_infra_name: strapi
mongo_infra_name: mongo-ha
dev_imagestream: digital-gov-frontend
prod_image_tag: prod 
test_image_tag: test 
github_environments:
  prod: production
  test: test
  dev: development