version: "3"

services:
  frontend:
    container_name: digital_frontend
    build: 
      context: ./react-frontend
      dockerfile: Dockerfile
    networks:
      - strapi-app-network
    volumes:
      - './react-frontend:/app'
      - /app/node_modules
    ports:
      - "3000:3000"
    tty: true
    
  backend:
    build: 
      context: ./strapi-app
      dockerfile: Dockerfile
    container_name: digital_backend
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - ./strapi-app:/srv/app
    ports:
      - "1337:1337"
    depends_on: 
      mongo:
        condition: service_started

  mongo:
    image: mongo:3.6.18-xenial
    container_name: digital_mongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - strapidata:/data/db
    ports:
      - "27017:27017"

networks:  
  strapi-app-network:
    driver: bridge

volumes:  
  strapidata:
