kind: Template
apiVersion: v1
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}${SUFFIX}:${IMAGE_TAG}'
      postCommit: {}
      resources: 
        requests:
          memory: 500Mi
          cpu: 250m
        limits:
          memory: 850Mi
          cpu: 300m
      runPolicy: Serial
      source:
        contextDir: react-frontend
        git:
          ref: ${GIT_REF}
          uri: ${GIT_REPO}
        type: Git
      strategy:
        sourceStrategy:
          env:
          - name: BUILD_LOGLEVEL
            value: "5"
          from:
            kind: ImageStreamTag
            name: caddy-s2i-builder:latest
          incremental: false
        type: Source
      successfulBuildsHistoryLimit: 5
      triggers:
        - type: ConfigChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ${NAME}${SUFFIX}
      name: ${NAME}${SUFFIX}
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      generation: 1
      labels:
        build: ${NAME}${SUFFIX}
      name: ${NAME}${SUFFIX}
      apiVersion: image.openshift.io/v1
parameters:
- name: IMAGE_TAG
  default: dev
  required: true 
  description: The output image tag for the buildconfig
  displayName: Image tag
- name: GIT_REF
  required: true
  description: The git branch the buildconfig is based off of 
  displayName: git ref
- name: GIT_REPO
  required: true
  value: https://github.com/bcgov/digital.gov.bc.ca
  description: The git repo the buildconfig is based off of 
  displayName: git repo
- name: NAME
  required: true
  default: digital-gov-frontend
  displayName: App name
  description: name for components (this will also change labels)
- name: SUFFIX
  required: true
  description: a suffix used in conjunction with NAME to further isolate different instances of these components
  displayName: suffix