---
  - hosts: localhost
    tasks:
      - name: check pr exists in tools 
        shell: oc -n {{ tools_namespace }} get imagestreamtag/{{ dev_imagestream }}:pr-{{ PR }}
        register: ist

      - fail: 
          msg: Image Tag pr-{{ PR }} does not exist
        when: "'No resources found' in ist.stdout"
      
      - name: deploy a dev instance of {{ PR }} in {{ dev_namespace }} namespace
        shell: >
          oc process -f "../templates/react-frontend/dc.yaml" --param-file="../templates/react-frontend/deploy.param" -p IMAGE_TAG="pr-{{ PR }}" | 
          oc apply -n "{{ dev_namespace }}" -f -