---
  - hosts: localhost
    tasks:
      - name: check if imagetag exists in tools 
        shell: oc -n {{ tools_namespace }} get imagestreamtag/{{ dev_imagestream }}:{{ IMAGE_TAG }}
        register: ist

      - fail: 
          msg: Image Tag {{ IMAGE TAG }} does not exist
        when: "'No resources found' in ist.stdout"
      
      - name: Retag image to test
        when: {{ ENV }} is test
        shell: >
          oc -n {{ test_namespace }} tag "{{ tools_namespace }}/{{ dev_imagestream }}:{{ IMAGE_TAG }}" {{ dev_imagestream }}:{{ test_image_tag }} && \
          oc -n {{ test_namespace }} rollout latest dc/{{ react_infra_name }}

      - name: Retag image to prod
        when: {{ ENV }} is prod
        shell: >
          oc -n {{ prod_namespace }} tag "{{ tools_namespace }}/{{ dev_imagestream }}:{{ IMAGE_TAG }}" {{ dev_imagestream }}:{{ prod_image_tag }} && \
          oc -n {{ prod_namespace }} rollout latest dc/{{ react_infra_name }

      