---
  - name: Fetch imagestream {{ strapi_infra_name }}:{{ version }} in namespace {{image_namespace}}
    shell: "oc -n {{image_namespace}} get istag {{ strapi_infra_name}}:{{version}}"
    register: output
    until: output.stdout.find("Error from server (NotFound)") == -1
    delay: 60
    retries: 20
    ignore_errors: True
  - name: Image Tag {{ version }} does not exist in {{ image_namespace }}. 
    debug: 
      msg: "The output is {{output}}. Image Tag {{ version }} does not exist in {{ image_namespace }}. \
           This is because either you have not run ansible-playbook build-strapi.yaml -e PR={{ PR }} \
           Or the buildconfig has been run but isn't complete \
           OR the build failed"
    when: "imagestreamtag|length == 0"
  - name: Setting image exists
    set_fact:
      image_exists: "imagestreamtag|length > 0"
