---  
  - name: Delete {{ react_infra_name }} of PR {{ PR }} in {{ namespace }} namespace
    shell: >
      oc delete -n "{{ namespace }}" all --selector pr={{ PR }}
  - debug: msg="Attempt to delete PR deployment failed"


  