# TODO GUT THIS AND HANDLE DELETION OF REACT IMAGE IN TOOLS NAMESPACE



---  
  - name: deploy {{ react_infra_name }} of PR {{ PR }} in {{ namespace }} namespace
    shell: >
      oc process -n "{{ namespace }}" -f "../openshift/templates/react-frontend/dc.yaml" {{ deploy_params }} | 
      oc apply -n "{{ namespace }}" -f -
    vars:
      IMAGE_TAG: '{{ version }}'
      deploy_params: "{{ lookup('template', './templates/deploy_react.param.j2') }}"
  - debug: msg="No image found"
    when: not image_exists
  