---
  - hosts: localhost
    vars:
      version: "{{ lookup('template', './templates/pr_tag.j2') }}"
      namespace: "{{ dev_namespace }}"
      suffix: "{{ version }}"
      image_namespace: "{{ tools_namespace }}"
    tasks:
      - name: check images
        include: ./tasks/check_image_exists.yaml
      - name: Delete PR Deployment
        include: ./tasks/delete_react_deployment.yaml
      # TODO delete the image, use delete_react_image.yaml