on:
  workflow_dispatch:
    paths:
    - 'react-frontend/src'
    - 'react-frontend/package.json'
  schedule:
    - cron: 0 0 1 * * # run monthly
  repository_dispatch: # run manually
    types: [check-link]
  # push:
  # ...

name: Broken Link Check
jobs:
  run:
    runs-on: ubuntu-latest
    env:    
      working-directory: ./react-frontend
    steps:
    - uses: actions/checkout@v1
    - name: build tests
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: Run url tests
      run: npm run url-test
      working-directory: ${{env.working-directory}}
    - name: Create team issue
      uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
      with:
        assignees: "thegentlemanphysicist"
        labels: "bug"
        title: "Team sync"
        body: |
          ### test issue
          - this should create an issur
        pinned: false
        close-previous: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
