on:
  workflow_dispatch:
    paths:
    - 'react-frontend/src'
    - 'react-frontend/package.json'
  schedule:
    - cron: 0 0 1 * * # run monthly
  repository_dispatch: # run manually
    types: [check-link]
  # push:
  # ...

name: Broken Link Check
jobs:
  run:
    runs-on: ubuntu-latest
    env:    
      working-directory: ./react-frontend
    steps:
    - uses: actions/checkout@v1
    - name: build tests
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: Run url tests
      run: npm run url-test
      working-directory: ${{env.working-directory}}
