name: Deploy to dev
on: [ pull_request]
jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: check
      run: echo $(pwd)
    - name: install oc
      # manually installing oc, i've opened up an issue with  github actions to include this since they
      # already have kubectl https://github.com/actions/virtual-environments/issues/1083
      run: |
        
        curl -O https://mirror.openshift.com/pub/openshift-v3/clients/3.11.232/linux/oc.tar.gz > oc.tar.gz
        tar xvzf oc.tar.gz 
        ls -l
        sudo mv oc /usr/local/bin
        rm oc.tar.gz
        oc version
    # TODO include ansible build and deploy play books as well as the creation of a github deployment on success
