name: Test Workflow Dispatch Works
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        required: true
        description: 'Test workflow dispatch tags'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps: 
      - name: 'test step'
        run: |
            echo "Log level: ${{ github.event.inputs.logLevel }}"
            echo "Tags: ${{ github.event.inputs.tags }}"
      # Check for write permission
      - name: Check user permission
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `check` step
      - name: Run only if user has sufficient permissions
        if: steps.check.outputs.has-permission
        run: echo "Congratulations! Your permissions to access the repository are sufficient."
      - name: Run only if user has NOT sufficient permissions
        if: "! steps.check.outputs.has-permission"
        run: echo "Sorry! Your permissions are insufficient."